name: Release to Github Packages. # https://ghcr.io
on: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
  workflow_dispatch:
  push:
    tags: # This builds for all branches with semantically versioned tags (v0.12.3).
      - 'v*' # https://semver.org will fail, if there are any other tags

  #release: # Builds only releases. Includes draft and pre-releases.
    #types: [created]

  #pull_request: # Run 'tests' for any PRs. Default is to not run for first-time contributors: see /settings/actions

env:
  TAG_LATEST: true # Encourage users to use a major version (foobar:1) instead of :latest.
  # By semantic versioning standards, major changes are changes 'backwards incompatible'. Major upgrades are often rare and prehaps, need attention from the user.
jobs:
  # Push image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Extract Builder meta
        id: builder-meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/itzderock/llama-playground
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.builder-meta.outputs.tags }}
          labels: ${{ steps.builder-meta.outputs.labels }}
